### PR TITLE
Ui tweak

### PR DESCRIPTION
**Pull request by pietrop**
before

Screen Shot 2020-04-28 at 8 29 51 PM

after

Screen Shot 2020-04-30 at 12 09 45 AM

for consistency with [`slate-transcript-editor`](https://github.com/pietrop/slate-transcript-editor)

Screen Shot 2020-04-29 at 11 39 38 PM

probl needs a designer input, but in the meanwhile this will do 🤷‍♂️

### CODE REVIEW

**Comment by emettely** [comment]
The button grouping seems really neat, sorry was taken aback by the colour though. Might benefit from harsher contrast. Slate's looking goood!

**Comment by pietrop** [comment]
Yeah, I think I might revert the color until I can get a designer to weight in, and merge the button grouping thing.

**Comment by pietrop** [comment]
Ok, going for this for now, hopefully it is an improvement, also tweaked the menu and used bootstrap `tooltip` instead of html `title` to do the sudgestions, coz it's more readable.

Screen Shot 2020-04-30 at 6 51 39 PM

**Comment by pietrop** [comment]
demo example at https://pietropassarelli.com/digital-paper-edit-client

**Comment by pietrop** [comment]
demo at http://pietropassarelli.com/digital-paper-edit-client/#/projects/10046281c4ad4938b7d0ae6fa9899bec/paperedits/86e938c468de4b0cb873c6e97a3a25f8

http://pietropassarelli.com/digital-paper-edit-client/

**Pull request merged**
